### ISSUE TITLE
ERROR] [Sponge]: Could not pass SpongeGameRegistryRegisterEvent

### ISSUE THREAD

**Issue by ziceptor** [gabizou/HappyTrails#3]
https://gist.github.com/ziceptor/0145995633471ed2d5ed6775a62cc29c

forge-1.12.2-14.23.1.2586-universal.jar
spongeforge-1.12.2-2586-7.1.0-BETA-2900.jar
HappyTrails-0.1.3.jar

**Comment by gabizou** [comment]
Bah silly validation checks.

**Comment by gabizou** [comment]
Fixed in v0.1.6
